--- #local 환경
spring:
  profiles:
    group:
      "local" : "default, api, security-api, database, logging, aws, secret"

--- #dev 환경
spring:
  profiles:
    group:
      "develop" : "default, api, security-api, database, logging, aws, secret"

--- #api 환경

spring:
  profiles:
    group:
      "release" : "default, api, security-api, database, logging, aws"



