## Spring boot actuator
spring:
  application.name: en9door-api-service
  main:
    allow-bean-definition-overriding: true


server:
  servlet:
    context-path: /api

eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    registryFetchIntervalSeconds: 5

jwt_secret: en9doorJwtTokenSecretKeyUsedInJWTProvider


---
spring.config.activate.on-profile: local
server:
  port: 24000

app:
  web-address: http://dev.investand.net:9090
  cors:
    allowed-origins: 'http://localhost:8080,http://dev.investand.net,http://dev.investand.net:9090'

baseUrl: https://dev.investand.net:24000

eureka:
  client:
    enabled: true     # enabled = false
    service-url:
      defaultZone: http://localhost:8761/eureka


---
spring.config.activate.on-profile: develop
server:
  port: 24001

baseUrl: https://dev.investand.net:24001


eureka:
  client:
    enabled: true     # enabled = false
    service-url:
      defaultZone: http://dev.investand.com:8761/eureka


---
spring.config.activate.on-profile: release
server:
  port: 24001

app:
  web-address: https://investand.net

baseUrl: https://investand.net/api


eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://dev.investand.com:8761/eureka