server:
  port: 24001


baseUrl: https://dev.investand.net:24001

springdoc:
  version: '1.0.0'
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  show-actuator: true
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

