spring:
  jpa: #JPA 설정
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        show_sql: false

---
spring.config.activate.on-profile: local

spring:
  jpa: #JPA 설정
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

db-investand:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://db.en9doors.com:3306/investand?characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode=true&createDatabaseIfNotExist=true
  username: ${db.username}
  password: ${db.password}


---
spring.config.activate.on-profile: develop

spring:
  jpa: #JPA 설정
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false          #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.

db-investand:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${db.url}
  username: ${db.username}
  password: ${db.password}
---
spring.config.activate.on-profile: release

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false          #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.

db-investand:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${db.url}
  username: ${db.username}
  password: ${db.password}