--- #dev 환경
spring:
  profiles:
    group:
      "local" : "default, security, local-core, secret"

--- #dev 환경
spring:
  profiles:
    group:
      "develop" : "default, security,develop-core, secret"

--- #api 환경

spring:
  profiles:
    group:
      "release" : "default, security,release-core, secret"



