spring:
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      max-lifetime: 160000
      connection-timeout: 10000
      validation-timeout: 10000
      connection-init-sql: set wait_timeout = 180
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 1000
  decorator:
    datasource:
      p6spy:
        logging: slf4j
        enable-logging: false
  jpa: #JPA 설정
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        #        dialect: org.hibernate.dialect.VoyagerssDBDialect  #방언 설정 https://dololak.tistory.com/465, https://gigas-blog.tistory.com/119
        format_sql: true        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        use_sql_comments: true        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
        jdbc:
          batch_size: 100
          time_zone: Asia/Seoul
  output:
    ansi:
      enabled: always

---
spring.config.activate.on-profile: local

spring:
  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: false          #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.

  r2dbc:
    url: r2dbc:pool:mysql://db.en9doors.com:3306/en9door?characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode=true&createDatabaseIfNotExist=true
    username: minssan9_release
    password: dydzhf104

  data:
    mongodb:
      host: voyagers.2ekpunp.mongodb.net
      port: 27017
      username: vue-til
      password: KP8D522n9d5STfky
      database: paul
#      authentication: database=admin

db-investand:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://db.en9doors.com:3306/investand?characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode=true&createDatabaseIfNotExist=true
  username: minssan9_release
  password: dydzhf104


---
spring.config.activate.on-profile: develop

spring:
  jpa:
    #    generate-ddl: true
    #    hibernate:
    #      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: false          #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
  r2dbc:
    url: jdbc:mysql://db.en9doors.com:3306/en9door?characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode=true&createDatabaseIfNotExist=true
    username: minssan9_release
    password: dydzhf104

db-en9door:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://db.en9doors.com:3306/en9door?characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode=true&createDatabaseIfNotExist=true
  username: ${db.develop.username}
  password: ${db.develop.password}
---
spring.config.activate.on-profile: release

spring:
  jpa:
    #    generate-ddl: true
    #    hibernate:
    #      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: false          #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
  r2dbc:
    url: jdbc:mysql://db.en9doors.com:3306/en9door?characterEncoding=utf8&serverTimezone=Asia/Seoul&useUnicode=true&createDatabaseIfNotExist=true
    username: minssan9_release
    password: dydzhf104

db-en9door:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${en9door_rds_url}
  username: ${en9door_rds_id}
  password: ${en9door_rds_pw}