spring:
  application:
    name: investand_api
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
#      ddl-auto: update
    generate-ddl: true
    show-sql: true

core:
  web-address: http://dev.investand.net

db-investand:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${db.develop.url}
  username: ${db.develop.username}
  password: ${db.develop.password}

devtools: #jsp파일 서버 재시작 없이 바로 적용하기  spring-boot-devtools
  livereload:
    enabled: true

#error / warn / debug / info / trace
logging:
  level:
    sql: warn
    p6psy.p6spy: warn
    root: info
  file:
    path: /var/log/${spring.application.name}-develop
    name: ${logging.file.path}/${spring.application.name}.log

